"""Initial migration

Revision ID: bce28c7fee7d
Revises: 
Create Date: 2023-07-10 02:56:03.401535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce28c7fee7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorija_proizvoda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narudzbina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cena', sa.REAL(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DATETIME(), nullable=False),
    sa.Column('porucilac', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proizvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=256), nullable=False),
    sa.Column('cena', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pripada_kategoriji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=False),
    sa.Column('kategorija_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategorija_id'], ['kategorija_proizvoda.id'], ),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pripada_narudzbini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=False),
    sa.Column('narudzbina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['narudzbina_id'], ['narudzbina.id'], ),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pripada_narudzbini')
    op.drop_table('pripada_kategoriji')
    op.drop_table('proizvod')
    op.drop_table('narudzbina')
    op.drop_table('kategorija_proizvoda')
    # ### end Alembic commands ###
