version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - authenticationNetwork
  authenticationdbinit:
    image: authenticationdbinit
    environment:
      - DATABASE_URL=database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - authenticationNetwork
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authenticationNetwork
      - storeNetwork
  prodavnicaDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - storeNetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  storedbinit:
    image: storedbinit
    environment:
      - DATABASE_URL=prodavnicaDatabase
    depends_on:
      prodavnicaDatabase:
        condition: service_healthy
    networks:
      - storeNetwork
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=database
    ports:
      - 5002:5002
    depends_on:
      - authenticationdbinit
    networks:
      - authenticationNetwork
  owner:
    image: owner
    environment:
      - DATABASE_URL=prodavnicaDatabase
    ports:
      - 5003:5003
    networks:
      - storeNetwork
    depends_on:
      - blockchain
  customer:
    image: customer
    environment:
      - PRODUCTION="PRODUCTION"
    ports:
      - 5004:5004
    networks:
      - storeNetwork
    depends_on:
      - blockchain
  courier:
    image: courier
    environment:
      - PRODUCTION="PRODUCTION"
    ports:
      - 5005:5005
    networks:
      - storeNetwork
    depends_on:
      - blockchain
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8082:8080
      - 7077:7077
    networks:
      - storeNetwork
    environment:
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      - storedbinit
  spark-worker-1:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-1
      depends_on:
        - spark-master
      ports:
        - 8083:8081
      networks:
        - storeNetwork
      environment:
        - SPARK_MASTER=spark://spark-master:7077
  spark-worker-2:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-2
      depends_on:
        - spark-master
      ports:
        - 8084:8081
      networks:
        - storeNetwork
      environment:
        - SPARK_MASTER=spark://spark-master:7077
  sparkapp:
      image: sparkapp
      environment:
        - PRODUCTION=True
        - SOCKET_IP=0.0.0.0
        - SOCKET_PORT=9090
        - SPARKAPP_IP=sparkapp
      ports:
        - 5006:5006
      networks:
        - storeNetwork
      depends_on:
        - storedbinit
  blockchain:
    image: trufflesuite/ganache-cli
    ports:
        - 8545:8545
    networks:
      - storeNetwork
    depends_on:
      - storedbinit
networks:
  authenticationNetwork:
  storeNetwork: