"""Dodato polje za ugovor

Revision ID: 7985e72a9c65
Revises: 0addc7395d48
Create Date: 2023-07-13 00:56:43.703625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7985e72a9c65'
down_revision = '0addc7395d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('narudzbina', sa.Column('ugovor', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narudzbina', 'ugovor')
    # ### end Alembic commands ###
